### ISSUE TITLE
[Bug] "PreferUpperCamelIfMissed" has some strange problem

### ISSUE THREAD

**Issue by neville1** [dougpuob/cpp-namelint#15]
When I set "PreferUpperCamelIfMissed = true", I will get error like this

  <11, 28> Variable :    u32StreamId (uint32_t)
  <105, 50> Parameter:    u8RxSeq (uint8_t)

**Comment by dougpuob** [comment]
This issue was fixed in this PR(https://github.com/dougpuob/cpp-namelint/pull/37/.)
