### ISSUE TITLE
[Bug] Shouldn't check define for Windows or VS

### ISSUE THREAD

**Issue by JeffHsu79** [dougpuob/cpp-namelint#16]
Some Example:
![image](https://user-images.githubusercontent.com/54425769/63563942-990bd800-c595-11e9-8b2b-defeae6a2dd7.png)
![image](https://user-images.githubusercontent.com/54425769/63563953-acb73e80-c595-11e9-8231-7eed4e04d0d4.png)

**Comment by dougpuob** [comment]
I never see this issue after version 0.3.x, I may fix at somewhere. (I tested it with source code SdTester utility).
