### ISSUE TITLE
[Bug] Some common define shouldn't be check

### ISSUE THREAD

**Issue by JeffHsu79** [dougpuob/cpp-namelint#20]
### **using name space std:**
![image](https://user-images.githubusercontent.com/54425769/63564078-2bac7700-c596-11e9-9ce2-c721d0fcba25.png)

### **__tmain2:**
![image](https://user-images.githubusercontent.com/54425769/63564091-3d8e1a00-c596-11e9-8381-e2a90629fcf4.png)

**Comment by dougpuob** [comment]
I never see this issue after version 0.3.x, I may fix at somewhere. (I tested it with source code SdTester utility).
