### ISSUE TITLE
[Bug] Parameter with only type will error in check

### ISSUE THREAD

**Issue by JeffHsu79** [dougpuob/cpp-namelint#21]
![image](https://user-images.githubusercontent.com/54425769/63564194-b3928100-c596-11e9-85a4-fdfabdcf6520.png)
![image](https://user-images.githubusercontent.com/54425769/63564211-c5742400-c596-11e9-8eb2-8762b7879e9c.png)

**Comment by dougpuob** [comment]
I never see this issue after version 0.3.x. (I tested it with source code SdTester utility).
