### ISSUE TITLE
[Bug] Some special case check error

### ISSUE THREAD

**Issue by JeffHsu79** [dougpuob/cpp-namelint#23]
![image](https://user-images.githubusercontent.com/54425769/63564828-374d6d00-c599-11e9-8923-54a8d3467a80.png)
![image](https://user-images.githubusercontent.com/54425769/63564874-61069400-c599-11e9-8435-9a5f7427f7f7.png)

###  macro using for parmeter:
![image](https://user-images.githubusercontent.com/54425769/63564963-b8a4ff80-c599-11e9-9994-77bf7b4132db.png)
![image](https://user-images.githubusercontent.com/54425769/63564986-d3777400-c599-11e9-9e88-430252f787ae.png)

### macro, but fail
![image](https://user-images.githubusercontent.com/54425769/63565073-1c2f2d00-c59a-11e9-9b88-803bb475fbf5.png)
![image](https://user-images.githubusercontent.com/54425769/63565157-5c8eab00-c59a-11e9-8cdd-8c4096382421.png)
![image](https://user-images.githubusercontent.com/54425769/63565192-82b44b00-c59a-11e9-89d8-eb4c06cf77d8.png)

### fail often in my code(same class)
![image](https://user-images.githubusercontent.com/54425769/63565298-040bdd80-c59b-11e9-90ce-de201ddbeced.png)
![image](https://user-images.githubusercontent.com/54425769/63565320-1b4acb00-c59b-11e9-9580-2baaf20acbce.png)

**Comment by dougpuob** [comment]
Similar to (https://github.com/dougpuob/cpp-namelint/issues/22), has fixed with the PR(https://github.com/dougpuob/cpp-namelint/pull/47).
