### ISSUE TITLE
[Bug] Config file with same name will fail

### ISSUE THREAD

**Issue by JeffHsu79** [dougpuob/cpp-namelint#26]
![image](https://user-images.githubusercontent.com/54425769/63677670-12b6f680-c820-11e9-8e70-848d0be60d51.png)
![image](https://user-images.githubusercontent.com/54425769/63677707-24000300-c820-11e9-82f4-6cc06faac3e1.png)

**Comment by dougpuob** [comment]
This issue was fxied at https://github.com/dougpuob/cpp-namelint/pull/35/ PR.


Add error occurred line information, like the following screenshot.
![image](https://user-images.githubusercontent.com/3453968/77894043-4f136f00-72a7-11ea-9aaa-209217a218be.png)
